// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	greeter2 "free-vibe-coding/internal/biz/greeter"
	"free-vibe-coding/internal/conf"
	"free-vibe-coding/internal/data"
	"free-vibe-coding/internal/data/greeter"
	"free-vibe-coding/internal/server"
	greeter3 "free-vibe-coding/internal/service/greeter"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	repo := greeter.NewRepo(dataData, logger)
	usecase := greeter2.NewUsecase(repo)
	service := greeter3.NewService(usecase)
	grpcServer := server.NewGRPCServer(confServer, service, logger)
	httpServer := server.NewHTTPServer(confServer, service, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
